### ISSUE TITLE
Armoured spearhead tech marine missing 

### ISSUE THREAD

**Issue by mech-warrior** [BattleScribe/Android-Alphas#10]
When selecting the space marine armoured spearhead the default techmarine is included - his points are there too - .... but when the formation is opened he is not avaliable / visible for upgrades etc  only the add on formation units options shows

**Comment by Jonskichov** [comment]
I think this should be fixed in build 147: https://github.com/BattleScribe/Android-Alphas/issues/1#issuecomment-210207330

Can you please confirm? (I'm not sure I'm testing the right spearhead!)

**Comment by Jonskichov** [comment]
Fixed it build 148: https://github.com/BattleScribe/Android-Alphas/issues/1#issuecomment-210207330
