### ISSUE TITLE
Security alert from Dropbox.

### ISSUE THREAD

**Issue by capitaladot** [BattleScribe/Android-Alphas#12]
"Another app on your phone may be trying to pose as the app you are currently using. The malicious app can't access yoir account, but linking Dropbox has been disabled as a precaution. Please contact support@dropbox.com"

**Comment by Jonskichov** [comment]
This is probably because you can't have multiple apps installed that link to the same Dropbox folder.

There is now a check for this that instructs you to disconnect other versions of the app before linking the new one.
