### ISSUE TITLE
Incorrect Transfer from 1.X to 2.0 data files <Skitarii Maniple Data files>

### ISSUE THREAD

**Issue by martijndoornik** [BattleScribe/Android-Alphas#15]
I have updated the data files from the previous version into the new Alpha version. However, when making lists for Skitarii, I get error messages that I have 1 too many Vanguard units and that I should have got at least 1 Ruststalker unit and 1 Infiltrator unit. Tested it with version 1.15.08 and works normal there. Might be a problem/conflict in converting the old file into the new format. 
![screenshot_20160811-093701](https://cloud.githubusercontent.com/assets/3370256/17581796/2d0cd736-5fa8-11e6-92db-fab62856f9f5.png)
![screenshot_20160811-093657](https://cloud.githubusercontent.com/assets/3370256/17581795/2d073704-5fa8-11e6-91fd-d87fce61e885.png)

**Comment by Jonskichov** [comment]
This is a known issue. The app is unable to deal with this particular situation during automatic data upgrade. It needs to be fixed manually by the data author.
