### ISSUE TITLE
Removing using holding/right top button causes crash <Minor>

### ISSUE THREAD

**Issue by martijndoornik** [BattleScribe/Android-Alphas#16]
When using the upper right remove bin button in a unit tab, the app crashes. This can be recreated with Warhammer 40.000's Eldar Corsairs. Under the elite section, there is a unit called the Voidstorm Squad. Individual characters can be adjusted by adding and removing them, rather than increasing or decreasing the number of characters. When selecting the character and trying to remove it with the bin on the upper right bin button, the app crashes

**Comment by Jonskichov** [comment]
This was fixed in 2.00.01
