### ISSUE TITLE
Advertising sometimes shows even when you've subscribed to Pro

### ISSUE THREAD

**Issue by Jonskichov** [BattleScribe/Android-Alphas#2]
Seems intermittent. The app should er on the side of _not_ showing ads if it can't yet verify your subscription.

**Comment by mech-warrior** [comment]
Mine shows adverts too

**Comment by Jonskichov** [comment]
Fixed in 144: https://github.com/BattleScribe/Android-Alphas/issues/1#issuecomment-208504559
