### ISSUE TITLE
Minimum quantity fault 

### ISSUE THREAD

**Issue by mech-warrior** [BattleScribe/Android-Alphas#4]
Just taken a fortifications and space marine test list - lots of items (lots and lots ) coming up with "minimum 1" error messages - almost all fortifications are doing this and quite a few marine ones

**Comment by Jonskichov** [comment]
Ah yes, this is a due to the way the data gets updated. I'm afraid that it's not possible for the update process to get around this. This issue needs to be manually fixed by the data authors.
